.PHONY: clean All

All:
	@echo "----------Building project:[ 17_diy_composite - Debug ]----------"
	@cd "C:\Users\David\Documents\learning_cpp\design_patterns\design_patterns\17_diy_composite" && "$(MAKE)" -f  "17_diy_composite.mk"
clean:
	@echo "----------Cleaning project:[ 17_diy_composite - Debug ]----------"
	@cd "C:\Users\David\Documents\learning_cpp\design_patterns\design_patterns\17_diy_composite" && "$(MAKE)" -f  "17_diy_composite.mk" clean
